agendamento/urls.py
from django.urls import path
from . import views

app_name = 'agendamento'

urlpatterns = [
    path('', views.listar_agendamentos_view, name='listar_agendamentos'),
    path('novo/', views.novo_agendamento_view, name='novo_agendamento')
]

base/urls.py
from django.urls import path
from . import views

app_name = 'base'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('cadastro/', views.cadastro_view, name='cadastro'),
    path('logout/', views.logout_view, name='logout'),
    path('home/', views.home_view, name='home'),
]

pyvid/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace='base')),
    path('agendamento/', include('agendamento.urls', namespace='agendamento'))
]

agendamento/models.py
from django.db import models
from datetime import date, datetime


class Agendamento(models.Model):
    estabelecimento_saude = models.ForeignKey('base.EstabelecimentoSaude', on_delete=models.CASCADE)
    data = models.DateField(verbose_name='Data de agendamento')
    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)


class AgendamentoUsuario(models.Model):
    agendamento = models.ForeignKey('Agendamento', on_delete=models.CASCADE)
    usuario = models.ForeignKey('base.Usuario', on_delete=models.CASCADE)
    data = models.DateField(verbose_name='Data de agendamento')
    horario = models.TimeField(verbose_name='Horário de agendamento')
    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    @property
    def status(self):
        if self.data < date.today():
            return 'Expirado'
        elif self.data == date.today():
            if self.horario < datetime.now().time():
                return 'Expirado'
            else:
                return 'Agendado'
        else:
            return 'Agendado'

base/models.py
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from localflavor.br.validators import BRCPFValidator
from localflavor.br.models import BRCPFField
from datetime import date


class UserManager(BaseUserManager):

    def _create_user(self, cpf, password, **extra_fields):

        if not cpf:
            raise ValueError("O CPF é obrigatório")

        cpf_validator = BRCPFValidator()
        cpf_validator(cpf)

        user = self.model(cpf=cpf, **extra_fields)
        user.set_password(password)
        user.save(using=self.db)
        return user


class Usuario(AbstractBaseUser, PermissionsMixin):
    USERNAME_FIELD = 'cpf'

    cpf = BRCPFField(verbose_name='CPF', primary_key=True)
    nome = models.CharField(verbose_name='Nome completo', max_length=255)
    data_nascimento = models.DateField(verbose_name='Data de nascimento')
    criado_em = models.DateTimeField(auto_now_add=True)
    atualizado_em = models.DateTimeField(auto_now=True)

    is_staff = models.BooleanField(default=False)
    active = models.BooleanField(default=True)

    objects = UserManager()

    @property
    def idade(self):
        today = date.today()
        return today.year - self.data_nascimento.year - ((today.month, today.day) < (self.data_nascimento.month, self.data_nascimento.day))


class EstabelecimentoSaude(models.Model):
    cnes = models.CharField(db_column='CO_CNES', max_length=7, unique=True, verbose_name='CNES')
    nome_fantasia = models.CharField(max_length=255)

    criado_em = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name='Criado em')
    atualizado_em = models.DateTimeField(auto_now_add=False, auto_now=True, verbose_name='Atualizado em')

    def __str__(self):
        return self.cnes + ' - ' + self.nome_fantasia

base/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from localflavor.br.forms import BRCPFField

from base.models import Usuario


class CadastroForm(UserCreationForm):
    cpf = BRCPFField()
    password1 = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = Usuario
        fields = ("nome", "cpf", "data_nascimento", "password1", "password2")


class LoginForm(forms.Form):
    cpf = BRCPFField()
    password = forms.CharField(widget=forms.PasswordInput())

agendamento/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from .models import Agendamento, AgendamentoUsuario
from datetime import date, datetime


@login_required(login_url='/')
def listar_agendamentos_view(request):
    agendamentos = AgendamentoUsuario.objects.filter(usuario=request.user)

    today = date.today()
    agora = datetime.now().time()
    quantidadeHoje = AgendamentoUsuario.objects.filter(usuario=request.user, data=today, horario__gt=agora).count()
    quantidade = AgendamentoUsuario.objects.filter(usuario=request.user, data=today, horario__gt=agora).count()

    for agendamento in agendamentos:
        print(agendamento.agendamento.estabelecimento_saude)

    return render(request, 'agendamentos.html', locals())


@login_required(login_url='/')
def novo_agendamento_view(request):
    today = date.today()
    agendamentos_ativos = AgendamentoUsuario.objects.filter(Q(data__gt=today) | Q(data=today, horario__gt=datetime.now().time()))

    if agendamentos_ativos.exists():
        return redirect('agendamento:listar_agendamentos')

    return render(request, 'novo_agendamento.html')

base/views.py
from django.shortcuts import render, redirect
from .forms import CadastroForm, LoginForm
from django.contrib.auth import views, authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages


def cadastro_view(request):
    form = CadastroForm(request.POST or None)

    if request.POST and form.is_valid():
        form.save()
        return redirect('base:home')

    return render(request, 'cadastro.html', locals())


def login_view(request):
    form = LoginForm(request.POST or None)

    if request.POST and form.is_valid():
        credentials = form.cleaned_data

        user = authenticate(username=credentials['cpf'], password=credentials['password'])

        if user is not None:
            login(request, user)
            return redirect('base:home')

        else:
            messages.warning(request, 'Usuário não encontrado.')
            return render(request, 'login.html', locals())

    return render(request, 'login.html', locals())


def logout_view(request):
    logout(request)
    return redirect('base:login')


@login_required(login_url='/')
def home_view(request):
    return render(request, 'home.html')

agendamento/templates/agendamentos.html
<!DOCTYPE html>
<html>
<head>
<title>Pyvid</title>
</head>
<body>
    <h1>Seus agendamentos</h1>
    <p><a href="{% url 'agendamento:novo_agendamento' %}">Novo agendamento</a></p>

    {% for agendamento in agendamentos %}
        <p>{{ agendamento.agendamento.estabelecimento_saude }}</p>
        <p>{{ agendamento.data }}</p>
        <p>{{ agendamento.horario }}</p>
        <br>
    {% endfor %}

</body>
</html>

agendamento/templates/novo_agendamento.html
<!DOCTYPE html>
<html>
<head>
<title>Pyvid</title>
</head>
<body>
    <h1>Novo agendamento</h1>

</body>
</html>

base/templates/cadastro.html
<!DOCTYPE html>
<html>
<head>
<title>Pyvid</title>
</head>
<body>

<h1>Se cadastre truta</h1>
<p>Já tem conta? <a href="{% url 'base:login' %}">Faça login</a></p>
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" />
</form>


</body>
</html>

base/templates/home.html
<!DOCTYPE html>
<html>
<head>
<title>Pyvid</title>
</head>
<body>
    <h1>Bem vindo {{ request.user.nome }}</h1>
    <p>nome: {{ request.user.nome }}</p>
    <p>cpf: {{ request.user.cpf }}</p>
    <p>data de nascimento: {{ request.user.data_nascimento }} ({{ request.user.idade }} anos)</p>
    <a href="{% url 'agendamento:listar_agendamentos' %}">Agendamento</a>
    <a href="{% url 'base:logout' %}">Sair</a>
</body>
</html>

base/templates/login.html
<!DOCTYPE html>
<html>
<head>
<title>Pyvid</title>
</head>
<body>

<h1>Bem-vindo Truta</h1>
<p>Novo por aqui? <a href="{% url 'base:cadastro' %}">Cadastre-se</a></p>

{% if messages %}
    {% for message in messages %}
        {{ message }}
    {% endfor %}
{% endif %}

<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" />
</form>

</body>
</html>